### ISSUE TITLE
Example isn’t available

### ISSUE THREAD

**Issue by kuka** [untra/polyglot#1]
Hey! 

First of all, thank you for the plugin.

You have listed an example with link leading to https://untra.github.io/polyglot, which is not open sourced. Can you add it as a public repo so we can see the structure and linking?

Thanks again.

**Comment by untra** [comment]
Hi @kuka !

The example website https://untra.github.io/polyglot is on my seperate [site](https://github.com/untra/polyglot/tree/site) branch. You can look at that to see the structure and linking. I will make that clearer in my readme, and I'll start a wiki with specific how-to steps.

Cheers!

**Comment by kuka** [comment]
@untra much appreciated!
