### ISSUE TITLE
Categories support

### ISSUE THREAD

**Issue by gijsroge** [untra/polyglot#10]
Am I right that there is currently no support for categories? 

Lets say I have:
* post-1.markdown (english category name) 
* post-2.markdown (english category name)

##### French folder:
  * post-1.markdown (french category name) 
  * post-2.markdown (french category name)

And if I loop trough my site.posts it will render 4 posts. 

Or is there a nice workaround for this?

**Comment by untra** [comment]
@gijsroge 

Polyglot does not provide formal support for multi-language categories. This does not mean you can't add it in yourself. There is a workaround using a string dictionary with keys set to the i18n language codes. See [this issue](https://github.com/untra/polyglot/issues/8) for more information.

This seems to be a popular request. I may update polyglot in the future to provide formal support for multi-language categories.

I hope this answers your question!

**Comment by gijsroge** [comment]
@untra Thanks, works fine indeed.
