### ISSUE TITLE
remove .lang from url and output

### ISSUE THREAD

**Issue by dseeker** [untra/polyglot#100]
If a project is using .lang file names standard it makes it mandatory to fill permalinks, otherwise files and urls retain with .lang names (/about-us.de.md, /about-us.fr.md). Usually we want to localize the url as well, but in some cases where the url stays the same across languages it would be great if this could be done automatically.

As a patch I have inserted a cleanLang method to remove the available languages from the files, thus allowing simple file name organization.

I don't know ruby and just kind of hacked together something, maybe you can take this into the next level and implement this in the polyglot library? I'll leave the code here in case it can be useful to others

https://github.com/untra/polyglot/pull/101

**Comment by dseeker** [comment]
@untra sorry I didn't get back, I've now expanded part of the library to make permalinks out of slugfied titles instead of file names. I'm wondering if there is a way to pass a param switch to enable or not making permalinks from titles

**Comment by untra** [comment]
yo @dseeker dawg let me know if you still want to get this in:
https://github.com/untra/polyglot/pull/101#issuecomment-588597235
