### ISSUE TITLE
I18n_Headers does not support ${lang}_${COUNTRY}

### ISSUE THREAD

**Issue by trombik** [untra/polyglot#106]
`I18n_Headers` generates `Content-Language` like the following:

```
<meta http-equiv="Content-Language" content="en">
```

which is valid. But some platforms use more specific values of the format `${lang}_${COUNTRY}`. Open Graph protocol also states that:

> The locale these tags are marked up in. Of the format language_TERRITORY. Default is en_US.

I don't know how it should be implemented (when you have `en` pages, which one should be used, `en_US`, or `en_GB`?). currently, I am using a custom logic with `site.data`.

`I18n_Headers` is just for shortcut, thus, not supporting `en_US` is one option. in that case, a note in `README.md` would be nice.

**Comment by untra** [comment]
heya @trombik 👋 

`en` is a [ISO 639-1](https://www.w3schools.com/tags/ref_language_codes.asp) identifier for english language, and would be used for english language content. However specific country codes can also be used in conjunction with a language, like `en_US` and `en_GB`.

In browsers, `en` , `en_US` and `en_GB` are all the same, but users may set browser preferences for `en_GB` content over `en_US` content. If you intend to make different language content for _united states english_ and _great britain english_ , then you would specify supporting `languages: ["en_US", "en_GB"]`.

If you intend to support two different kinds of english language on your website, that's how you would do it. The country code is optional, and british SEO may favor `en_GB` content over `en_US` content.

In general though, you should just use `en` for english.

**Comment by untra** [comment]
@trombik lemme know if you have any further questions around this, otherwise I'm gonna close this issue. Cheers
