### ISSUE TITLE
No windows support

### ISSUE THREAD

**Issue by LsKs** [untra/polyglot#11]
I'm trying to get polyglot to run on my windows machine, however it fails with the following error:

`C:/Users/kamilw/Dev/pryw/_plugins/polyglot.rb:29:in "fork": fork() function is unimplemented on this machine (NotImplementedError)
	from C:/Users/kamilw/Dev/pryw/_plugins/polyglot.rb:29:in "block in process"
	from C:/Users/kamilw/Dev/pryw/_plugins/polyglot.rb:28:in "each"
	from C:/Users/kamilw/Dev/pryw/_plugins/polyglot.rb:28:in "process"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.1/lib/jekyll/command.rb:26:in "process_site"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.1/lib/jekyll/commands/build.rb:60:in "build"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.1/lib/jekyll/commands/build.rb:33:in "process"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.1/lib/jekyll/commands/serve.rb:34:in "block (2 levels) in init_with_program"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in "call"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in "block in execute"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in "each"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in "execute"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in "go"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in "program"
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/jekyll-3.1.1/bin/jekyll:13:in "<top (required)>"
	from C:/Ruby22-x64/bin/jekyll:23:in "load"
	from C:/Ruby22-x64/bin/jekyll:23:in "<main>"`

I'm not a Ruby dev at all, but from I read it's because fork() is not a windows-compatible function.

**Comment by untra** [comment]
Yeah, that makes sense. Fork is exclusively a *nix command. Hmm...

Part of the trickyness is how windows and *nix create background processes. Windows doesn't implement `fork()`. I actually never tested this on a windows machine, but it makes sense it wouldn't work. Damn.

I'll think about finding a solution for this. A quick fix would be to take away the parallelism on windows machines, or at least providing a command line option to deny parallel compiling. That would mean fork never gets called, and the plugin would work (although not efficiently for huge Jekyll sites). @LsKs Can I ask how many languages you're trying to implement with polyglot, and how much content you have written for your Jekyll site already?

Good catch :+1:

**Comment by LsKs** [comment]
I've read that you can use spawn() instead (it actually really reminds me of Node.js child-process creation), but as I say that's my first step into the Ruby world so I have no idea. 

For now, I was trying to implement only 3 languages on a single landing page (with blog in the future), so there's not really much content.

**Comment by LsKs** [comment]
I could just possibly use your plugin on my OS X machine, but thought it could be essential to fix the problem for future windows users.

**Comment by recallfx** [comment]
Hi, I have made a quick workaround #15 that at least woks in windows.

**Comment by untra** [comment]
Thanks @recallfx for all of your help. I implemented most of those changes in #16.
Cheers!
