### ISSUE TITLE
Support liquid tags `t` similar to multiple-languages plugin

### ISSUE THREAD

**Issue by pke** [untra/polyglot#114]
This plugin seems to be only able to translate pages and posts in whole, not individual parts using liquid directives like `{% t key %}`?

**Comment by untra** [comment]
Yes, this plugin is focused on helping entire pages and posts be translated.

You can use your data directory and refer to language specific rich-text strings though. See the site directory for more details

**Comment by george-gca** [comment]
In my case I migrated my code from using [jekyll-multiple-languages-plugin](https://github.com/kurtsson/jekyll-multiple-languages-plugin/) to use `polyglot`. Previously I used a lot of `{% t key %}`, but now not so much is needed. Where I still wanted to use that approached what I did was:

- moved my keys from `_i18n/LANG.yml` to `_data/LANG/strings.yml`
- use them as `{{ site.data[site.active_lang].strings.key }}`

**Comment by george-gca** [comment]
I believe this can be closed now.
