### ISSUE TITLE
Will not exclude jekyll-assets folder

### ISSUE THREAD

**Issue by pudo** [untra/polyglot#12]
Thanks for your great plugin. I'm trying to use it with a site that also makes use of [jekyll-assets](https://github.com/jekyll/jekyll-assets). This mostly works fine, except the ``exclude_from_localization`` setting does not seem to apply to the output folder of ``jekyll-assets``, i.e the folder gets reproduced in each language copy of the project. Can you give me any advice for how to have only one folder?

**Comment by untra** [comment]
Hi @pudo !

In your assets configuration, you should have a value somewhere that looks like `prefix: /assets` or whatever you named the `jekyll-assets` output folder to be. Is that folder also listed in your `exclude_from_localization` array?

Better yet, is your jekyll project on github? I'll take a look at it.

**Comment by pudo** [comment]
Thanks for the quick response, @untra! Here's what I have so far: https://github.com/occrp/occrp.org-jekyll/blob/master/_config.yml - my plan is to not build the fake language "zz" at all, it's just there so the default language gets a prefix, too. But even without that, the assets directory is replicated in each language dir.

**Comment by untra** [comment]
It looks like the [occrp.org-jekyll](https://github.com/occrp/occrp.org-jekyll) is a private repo. I don't have permissions to look at it :/

**Comment by pudo** [comment]
Sorry! It's public now.

**Comment by untra** [comment]
Huh, It looks like you have "assets" listed in both your `exclude_from_localization` and `prefix` fields. I'll take a look at this more in depth this weekend, when I have some spare time. I haven't done any testing with jekyll-assets, but Its a popular repo, and worth making sure it cooperates with polyglot. :+1:

Thanks @pudo!

**Comment by pudo** [comment]
Thanks very much - and sorry for the bad issue description, I'm not a Ruby guy...

**Comment by untra** [comment]
I hope I've been of help. This is partially a problem of jekyll-assets. Let me know if you have any questions or concerns!

**Comment by pudo** [comment]
Thanks, yes! We didn't end up using polyglot after all, instead using a few snippets of bespoke ruby. Many thanks for your support, though!
