### ISSUE TITLE
[HELP] Conflict: The following destination is shared by multiple files.

### ISSUE THREAD

**Issue by CSYoungbin** [untra/polyglot#125]
Hi, I have trouble to use this plugin since I get this Conflict error.

I installed this with gem and bundler. After I installed it, I tried to 
1) bundle exec jekyll serve
2) and notice my blog does not organized like below

![Capture](https://user-images.githubusercontent.com/61127408/102317007-82cd1c80-3f3c-11eb-990e-0ba8d5cf8f7d.PNG)

3) and noticed I got this conflict on terminal.

![Capture](https://user-images.githubusercontent.com/61127408/102317284-ec4d2b00-3f3c-11eb-954f-11f338b029ec.PNG)

Can somebody let me know how to solve this problem?
(Btw I am using clone blog theme.)

Thanks advance.

**Comment by untra** [comment]
Hi @CSYoungbin 👋
We identified this issue in the past. The solution is to disable the css sourcemap generation:
https://github.com/untra/polyglot#compatibility

Let me know if this helps!
Cheers,
Untra

**Comment by CSYoungbin** [comment]
Thanks!
