### ISSUE TITLE
`relative_url_regex` regex error

### ISSUE THREAD

**Issue by JesusMtnez** [untra/polyglot#13]
I am trying to use this plugin in my jekyll blog.

- First I tried to use the gem. It didn't work.
- So I use the plugin file `polyglot.rb`. I placed it in my `_plugins` folder.

But when I try to build my blog, I get the following error:

![screen shot 2016-03-20 at 15 31 08](https://cloud.githubusercontent.com/assets/8639179/13904926/3d4e8af8-eeb1-11e5-997f-3326ebd920d0.png)

I'm not a ruby expert. It looks like there's something wrong in the method [`relative_url_regex`](https://github.com/untra/polyglot/blob/master/lib/polyglot.rb#L138-L145) in [line 144](https://github.com/untra/polyglot/blob/master/lib/polyglot.rb#L144):
```ruby
%r{href=\"#{site.baseurl}\/((?:#{n}[^,'\"\s\/?\.#-]+\.?)*(?:\/[^\]\[\)\(\"\'\s]*)?)\"}
```

Any idea?
Thank you for your time.

**Comment by untra** [comment]
@JesusMtnez Can you post that full error please? The regex actually changes based on what files are in your `exclude` list, and something tells me a file is screwing it up.

Is your project on github? Can I look at it?

**Comment by JesusMtnez** [comment]
@untra Thank you for your answer. Of course, you can find my blog in: [jesusmtnez.github.io](http://jesusmtnez.github.io)

**Comment by untra** [comment]
I see it. I'm not accounting for glob-matched filenames in my regex, which is apparently allowed when listing files with `exclude:` configuration. This is a bug on my part. Good find!

In the meantime, you can get polyglot working by removing anything matched with a wilcard `*` in your [exclude list](https://github.com/JesusMtnez/jesusmtnez.github.io/blob/master/_config.yml#L87). Namely, it's the `"*.sublime-project", "*.sublime-workspace"` that are causing the regex to break.

**Comment by JesusMtnez** [comment]
@untra You were right. I commented `exclude` and it works!

**Comment by JesusMtnez** [comment]
@untra I see. Good to know! I will remove them and continue with my blog. Thank you for your attention. I'm sorry but I can't fix this issue, since I don't know ruby. But I'm glad I helped to detected.

Thank you again.

P.S.: Great plugin, by the way! :+1:

**Comment by untra** [comment]
Glad you like it. I'm sorry the gem isn't working at the moment. I'm compiling a list of features and fixes for a new version of this plugin based on user feedback and extreme edge-cases. At the moment it's not conforming to a lot of jekyll standards, and relies on a few too many hacky ruby tricks (such as a dynamically changing regex).

Let me know if you have any other trouble!
@untra
