### ISSUE TITLE
Type-on-Strap theme modified for multilingual use

### ISSUE THREAD

**Issue by musicmichaelc** [untra/polyglot#139]
Hi, here is a jekyll theme that I have tweaked so that it will work multilingually, especially together with your polyglot plugin:

[Fork / modified version of Type-on-Strap](https://github.com/musicmichaelc/Type-on-Strap/tree/master)

**Comment by untra** [comment]
This is cool! if you have an example multilingual website up and running this I'll add a link to it in the readme here.

cheers,
Sam Volin
