### ISSUE TITLE
Baseurl modified with locale string leading to broken URLs with two locales

### ISSUE THREAD

**Issue by MSchmidt** [untra/polyglot#14]
E.g. while being on ``example.com/es`` ``baseurl`` is modified to include ``/es`` which leads to URLs with ``/es/es``.

This is used in head.html on your example page:
```
  <link rel="alternate"
        hreflang="{{site.default_lang}}"
        href="{{ site.baseurl }}/{{page.permalink}}" />
  {% for lang in site.languages %}
  {% if lang == site.default_lang %}
    {% continue %}
  {% endif %}
  <link rel="alternate"
      hreflang="{{lang}}"
      href="{{ site.baseurl }}/{{lang}}/{{page.permalink}}" />
  {% endfor %}
```

Which generated this:

```
<link rel="alternate" hreflang="en" href="/polyglot/es/">
<link rel="alternate" hreflang="es" href="/polyglot/es/es/">
<link rel="alternate" hreflang="de" href="/polyglot/es/de/">
<link rel="alternate" hreflang="fr" href="/polyglot/es/fr/">
```

I'm not sure if this is a problem with the plugin or with the example page but either way I thought I'd let you know.

**Comment by untra** [comment]
Ah! Nice catch! :+1:  It's a problem with the example page. I changed the code to what it should have been:
```
<link rel="alternate"
        hreflang="{{site.default_lang}}"
        href="{{ site.url }}/{{page.permalink}}" />
  {% for lang in site.languages %}
  {% if lang == site.default_lang %}
    {% continue %}
  {% endif %}
  <link rel="alternate"
      hreflang="{{lang}}"
      href="{{ site.url }}/{{lang}}/{{page.permalink}}" />
  {% endfor %}
```
It was supposed to be `site.url`, which corresponds to `https://untra.github.io/polyglot` in the `_config.yml`. I fixed the example page.

**Comment by MSchmidt** [comment]
Nice. Thanks for fixing this. I don't really understand it though. In the sidebar you are using ``site.baseurl`` as well and there is works just as expected. Why does it behave differently in head.html?

**Comment by MSchmidt** [comment]
I'm trying to use the new ``I18n_Headers`` helper of ``1.2.0`` and this issues seems to return with it.

This is what it creates when I'm on the ``/de`` path:
```
<meta http-equiv="Content-Language" content="de"><link rel="alternate" i18n="en" href="/de/" />
<link rel="alternate" i18n="de" href="/de/de/" />
```

**Comment by untra** [comment]
Check the permalinks on your pages.  Make sure they're identical on both the English and German pages.

**Comment by MSchmidt** [comment]
Got it to work by adding an URL to the helper: ``{% I18n_Headers https://example.com/ %}``

**Comment by untra** [comment]
Let me know if you're having other problems with the I18n_headers tag.  Other users reported problems with tags doubling up like the /de/de you mentioned.
