### ISSUE TITLE
Anchor links broken?

### ISSUE THREAD

**Issue by dougieh** [untra/polyglot#149]
Are hrefs containing an #anchor link supported by polyglot relativization?  

e.g. this works great and will correctly go to /about, /es/about, /fr/about etc.:
`<a href="/about">About</a>`

But this will always route to the root of the site (/about) regardless of active language:
`<a href="/about#team">About</a>`

I'm guessing the presence of the anchor hash mark breaks a regex somewhere?

**Comment by untra** [comment]
Hi @dougieh 
I just checked the site and tests, but I do not see any examples of relativizing anchor tags

https://polyglot.untra.io/2021/07/17/polyglot-1.5.0/#thanks
https://polyglot.untra.io/es/2021/07/17/polyglot-1.5.0/#gracias

> I'm guessing the presence of the anchor hash mark breaks a regex somewhere?

Yeah, I think it does indeed. :/ sorry about that.

heres that regex in question:
https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L178-L194

and the tests:
https://github.com/untra/polyglot/blob/master/spec/jekyll/polyglot/patches/jekyll/site_spec.rb#L58-L140

_good luck cowboy_ 🤠

**Comment by dougieh** [comment]
#150 should fix this!
