### ISSUE TITLE
fork error on windows with parallel_localization disabled

### ISSUE THREAD

**Issue by DukeDukeEm** [untra/polyglot#163]
Hi,

I have problems running my project with your gem. I basically get the same error as in #50
but my `parallel_localization` is already set to `false`

My project: https://github.com/DukeDukeEm/dukedukeem.github.io

This only happens when I try to run it on my local Win7 machine, pushing the project to github pages throws an [relative_url_regex error](https://github.com/DukeDukeEm/dukedukeem.github.io/runs/7872755256?check_suite_focus=true)

Please advise

**Comment by untra** [comment]
https://github.com/DukeDukeEm/dukedukeem.github.io/blob/main/_config.yml#L204-L209
your config settings are namespaced under `jekyll-polyglot:` which is not used by the yaml config in detecting settings. I'm not sure any of these settings will be picked up and respected.

remove line `204` and move the rest of that config flush to the left.

**Comment by DukeDukeEm** [comment]
Thank you.
Now I get the same error as in the github action. 
I guess something in my configured baseurl isn't right, but I can't see what, because I do not use an GitHub Pages Project sites and do not have an custom domain defined.

**Comment by DukeDukeEm** [comment]
Since my wrongly configured _config.yml is working now I thank you very much helping me with this, for the remaining problem I will open another request, I hope you find the time to help me with my second problem too.
