### ISSUE TITLE
github pages support ruby 2.7

### ISSUE THREAD

**Issue by meansoup** [untra/polyglot#196]
After add polyglot to my blog, it works if I changed ruby version to 3.
but, at 2 it doesn't work.
I use github pages, but github support ruby 2.7 for github pages.

Do you have any idea to use polyglot at github pages?

**Comment by untra** [comment]
Hi @meansoup ,

[these are the required ruby/rubygems/jekyll](https://github.com/untra/polyglot/blob/master/jekyll-polyglot.gemspec#L12-L14) polyglot requires. If you are experiencing a build issue, try following the stacktrace.

polyglot requires ruby >= 2.4, so I would expect it to build with ruby 2.7 . Is another ruby gem dependency requiring ruby >= 3 ? I can help further if you post and follow any stacktraces or debug errors.

Hopefully this helps

**Comment by meansoup** [comment]
@untra 
Thank you for reply.
I tested it several times, but it failed when I added polyglot to gem and config.

Because I was out of office now, I couldn't attach log, but I remember the log.
`fork() is not implemented` error.

If it is not enough to figure out the issue, I will attach log.

**Comment by untra** [comment]
`fork() is not implemented` is usually because you are running on windows.
https://github.com/untra/polyglot#compatibility

be sure to set `parallel_localization: false` in your config. Try that and lemme know what you find.

**Comment by meansoup** [comment]
@untra 
There was a typo in the property I used, thank you.
