### ISSUE TITLE
The polyglot works in local, but it doesn't work in github pages

### ISSUE THREAD

**Issue by meansoup** [untra/polyglot#198]
I run the jekyll in my windows, I could check the polyglot page.
But it shows 404 at github pages.

Do you have any idea?

**Comment by untra** [comment]
> get whitelisted as an official github-pages jekyll plugin

This is a primary goal of a future 2.0 release of polyglot. This plugin is developed independent of Jekyll and GitHub, and I have gotten a cold response from them in the past for getting whitelisted as an allowed gem.

GitHub pages doesn't support using polyglot natively. Instead you should deploy your built site with polyglot to a GitHub pages hosted directory.

**Comment by meansoup** [comment]
@untra Thank you for your fast reply.
I will wait for that.
