### ISSUE TITLE
`relative_url_regex': target of repeat operator is not specified

### ISSUE THREAD

**Issue by hynrng** [untra/polyglot#204]
Hello, thank you for a great plugin. I would love to try this plugin for my Jekyll blog.

<br>

However unfortunately I'm facing the following error:
```
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/jekyll-polyglot-1.8.0/lib/jekyll/polyglot/patches/jekyll/site.rb:234:in
`relative_url_regex': target of repeat operator is not specified: /href="?\/((?:(?!*.gem)(?!*.gemspec)(?!docs)(?!tools)
(?!README.md)(?!LICENSE)(?!*.config.js)(?!package*.json)(?!.sass-cache)(?!.jekyll-cache)(?!gemfiles)(?!Gemfile)
(?!Gemfile.lock)(?!node_modules)(?!vendor\/bundle\/)(?!vendor\/cache\/)(?!vendor\/gems\/)(?!vendor\/ruby\/)
(?!_data\/)(?!_includes\/)(?!_plugins\/)(?!_sass\/)(?!_tabs\/)(?!.github\/)(?!assets\/)(?!en\/)
(?!ko\/)[^,'"\s\/?.]+\.?)*(?:\/[^\]\[)("'\s]*)?)"/ (RegexpError)
```

It seems the following code is causing the error,
```
def relative_url_regex(disabled = false)
  regex = ''
  unless disabled
    @exclude.each do |x|
      regex += "(?!#{x})"
    end
    @languages.each do |x|
      regex += "(?!#{x}\/)"
    end
  end
  start = disabled ? 'ferh' : 'href'
  %r{#{start}="?#{@baseurl}/((?:#{regex}[^,'"\s/?.]+\.?)*(?:/[^\]\[)("'\s]*)?)"}
end
```

However I don't think fixing the code would help.

for the information, my `_config.yml` file is like:
```
plugins:
  - jekyll-polyglot

languages: ["en", "ko"]
default_lang: "ko"
exclude_from_localization: ["_data", "_includes", "_plugins", "_sass", "_tabs", ".github", "assets"]
parallel_localization: false
```

---

I've followed the another [issue seems related with my situation](https://github.com/untra/polyglot/issues/173) (removing "*.gem" and "*.gemspec" from `_config.yml`) but it didn't help.
(I'm using Ruby 3.3.0, jekyll 4.3.3, and working on Windows.)

**Comment by untra** [comment]
Hello @hynrng 👋 

The problem is `.github` in the `exclude_from_localization` configuration. That is used to build a regex and the `.` in a directory name is likely not handled well.

However that config is for directories you want included _only once_ in your built jekyll site, and not localized for N many languages.

You should instead specify the `.github` directory as part of the `exclude` [ configuration for jekyll](https://jekyllrb.com/docs/configuration/options/#global-configuration) if you specifically want that directory excluded from the built site, which is what I think you want.

I hope this helps and makes sense!

**Comment by hynrng** [comment]
Thank you for your detailed response.

However, although I read your response carefully, I am still under the same problem.
My understanding is that  need to add `.github` to the `exclude:` part of `_config.yml`, but I'm still getting the same error.

I'm really sorry, but could you help me a little more? I would really like to try this plugin.

**Comment by untra** [comment]
looking closer, when I run the regex in your error
```
/href="?\/((?:(?!*.gem)(?!*.gemspec)(?!docs)(?!tools)
(?!README.md)(?!LICENSE)(?!*.config.js)(?!package*.json)(?!.sass-cache)(?!.jekyll-cache)(?!gemfiles)(?!Gemfile)
(?!Gemfile.lock)(?!node_modules)(?!vendor\/bundle\/)(?!vendor\/cache\/)(?!vendor\/gems\/)(?!vendor\/ruby\/)
(?!_data\/)(?!_includes\/)(?!_plugins\/)(?!_sass\/)(?!_tabs\/)(?!.github\/)(?!assets\/)(?!en\/)
(?!ko\/)[^,'"\s\/?.]+\.?)*(?:\/[^\]\[)("'\s]*)?)"/
```

through [regexr](https://regexr.com/) I see it highlights the `*.gem` and `*.gemspec` that you took out. It also flags `*.config.js` which I don't see you mentioned anywhere in your config, but that value is being included and problematic to the built regex. Try taking that out wherever you may have specified it:

<img width="1313" alt="Screenshot 2024-05-30 at 8 15 03 AM" src="https://github.com/untra/polyglot/assets/3855429/c4ea6b79-9d87-4492-ba64-287cc6996f15">

**Comment by hynrng** [comment]
Sorry, I didn't say enough.
I'm using [Chirpy theme](https://github.com/cotes2020/jekyll-theme-chirpy) and by default, it excludes:

```
- "*.gem"
- "*.gemspec"
- docs
- tools
- README.md
- LICENSE
- "*.config.js"
- package*.json
```

and I guess those with the wildcard are causing the problem. I tried take them out, and sure enough, the page builds without ``relative_url_regex': target of repeat operator is not specified` error, but it ends up being broken.

**Comment by untra** [comment]
I would say that this is a bug in the chirpy theme:
https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/_config.yml#L211-L217

exclude entries are supposed to be file or directory names, not glob patterns.
https://jekyllrb.com/docs/configuration/options/#global-configuration

either the jekyll documentation is wrong, or chirpy theme excludes are not working correctly. I would open a bug in that project and ask this questions

**Comment by hynrng** [comment]
Thank you for your detailed explanation of the cause 🙂

It seems there is nothing I can do. It's unfortunate, but I'd better to wait for the issue to be resolved. Thank you for your sincere response.

**Comment by hynrng** [comment]
## **Problem solved**

I discovered other jekyll themes such as [miminal-mistakes](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L168-L169) are using flob patterns on `exlude:` section.

So, rather than open an issue on Chirpy theme, I edited the `site.rb` code like:

- `relative_url_regex`

  ```
  def relative_url_regex(disabled = false)
    regex = ''
    unless disabled
      @exclude.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x})"
      end
      @languages.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x}\/)"
      end
    end
    start = disabled ? 'ferh' : 'href'
    %r{#{start}="?#{@baseurl}/((?:#{regex}[^,'"\s/?.]+\.?)*(?:/[^\]\[)("'\s]*)?)"}
  end
  ```

- `absolute_url_regex()`

  ```
  def absolute_url_regex(url, disabled = false)
    regex = ''
    unless disabled
      @exclude.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x})"
      end
      @languages.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x}\/)"
      end
    end
    start = disabled ? 'ferh' : 'href'
    %r{(?<!hreflang="#{@default_lang}" )#{start}="?#{url}#{@baseurl}/((?:#{regex}[^,'"\s/?.]+\.?)*(?:/[^\]\[)("'\s]*)?)"}
  end
  ```
  
  and now it works fine. If someone is having the same situation as mine, I hope these solutions will help, even if only temporarily.

**Comment by hynrng** [comment]
## **Problem solved**

I discovered other jekyll themes such as [miminal-mistakes](https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml#L168-L169) are using flob patterns on `exlude:` section.

So, rather than open an issue on Chirpy theme, I edited the `site.rb` code like:

- `relative_url_regex`

  ```
  def relative_url_regex(disabled = false)
    regex = ''
    unless disabled
      @exclude.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x})"
      end
      @languages.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x}\/)"
      end
    end
    start = disabled ? 'ferh' : 'href'
    %r{#{start}="?#{@baseurl}/((?:#{regex}[^,'"\s/?.]+\.?)*(?:/[^\]\[)("'\s]*)?)"}
  end
  ```

- `absolute_url_regex()`

  ```
  def absolute_url_regex(url, disabled = false)
    regex = ''
    unless disabled
      @exclude.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x})"
      end
      @languages.each do |x|
        escaped_x = Regexp.escape(x)
        regex += "(?!#{escaped_x}\/)"
      end
    end
    start = disabled ? 'ferh' : 'href'
    %r{(?<!hreflang="#{@default_lang}" )#{start}="?#{url}#{@baseurl}/((?:#{regex}[^,'"\s/?.]+\.?)*(?:/[^\]\[)("'\s]*)?)"}
  end
  ```
  
  and now it works fine. If someone is having the same situation as mine, I hope these solutions will help, even if only temporarily.

**Comment by ameaninglessname** [comment]
> If someone is having the same situation as me, I hope these solutions will help, although it might not a fundamental solution.

Thanks! It works for me.



To be clear, the `site.rb` is located at:
```
D:\Ruby\lib\ruby\gems\3.3.0\gems\jekyll-polyglot-1.8.0\lib\jekyll\polyglot\patches\jekyll\site.rb
```
(You can't find `absolute_url_regex` elsewhere though)
