### ISSUE TITLE
A bug of I18n_Headers tag

### ISSUE THREAD

**Issue by blackpill** [untra/polyglot#208]
I've found a bug of I18n_Headers tag.

If the permalink of a page is assigned to 'xxx', 
the hreflang for default_lang is wrong, like `<link rel="alternate" hreflang="en" href="https://polyglot.untra.ioseo/"/>`, missed a "/"
We can see the bug from the source code of [https://polyglot.untra.io/seo/](https://polyglot.untra.io/seo/)

If the permalink of a page is assigned to '/xxx', 
the hreflang for other languages are wrong, like `<link rel="alternate" hreflang="es" href="https://polyglot.untra.io/es//seo/"/>`

Please fix this minor bug. Thank you!

**Comment by george-gca** [comment]
So why is it working on the page?

**Comment by blackpill** [comment]
If the permalink of a page is assigned to 'xxx/',
the hreflang for default_lang is wrong, like <link rel="alternate" hreflang="en" href="https://polyglot.untra.ioseo/"/>, missed a "/"
We can see the bug from the source code of https://polyglot.untra.io/seo/

**Comment by untra** [comment]
Nice find @blackpill ! fix should be deployed in 1.8.1
