### ISSUE TITLE
Disable `parallel_localization`

### ISSUE THREAD

**Issue by veblush** [untra/polyglot#21]
Hello!

I want to disable `parallel_localization` but it seems impossible to turn it off in `_config.yml`.
[site.rb](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L11) has a configuration for this but it always gets `true` because of statement, ```config || true```

Please check this :smile: and thanks for your work!

**Comment by untra** [comment]
You're totally right.  Good catch! false OR true is always true.  Rookie mistake, doh! 

I'm on a trip at the moment. I'm away from my computer for the next few days (but I have a smartphone and Internet connection).  If you can make a pr with the right changes, I'll merge it in. :+1:

It won't update the gem though. I gotta figure out...

**Comment by veblush** [comment]
Ok I made a [PR](https://github.com/untra/polyglot/pull/22).
It was the first time for me to write ruby code.

**Comment by untra** [comment]
Thanks for your good code and PR! Contributing to open source projects is pretty exciting.  I really appreciate your help,  and I'll update the README with your username when I have computer access. 

Cheers!

**Comment by veblush** [comment]
Thanks! I also appreciate your great product and it was a good experience
to learn how jekyll and ruby work :).
Have a good trip!
