### ISSUE TITLE
language-specific content & fallbacks

### ISSUE THREAD

**Issue by ioab** [untra/polyglot#24]
Hi ! 
Thanks for the great help by making polyglot ! 

I'm wondering about a couple of things though:
- Shouldn't specific-language posts be kept for that language version only ?
  I mean, if I needed to write some post in language X, is there a way of hiding it from appearing in Y's language Index ? 
  This snippet in index.html demonstrate the point:

``` html
 {% for post in paginator.posts | where: "lang", "{{ site.active_lang }}" %}
  <div class="post">
    <h1 class="post-title">
      <a href="{{ post.url }}">
        {{ post.title }}
      </a>
    </h1>
    <span class="post-date">{{ post.date | date_to_string }}</span>
    {{ post.content }}
  </div>
  {% endfor %}
```
- Right now, the fallback behavior appears to be overriding this filtering (?). 
  and fallback seems to be bidirectional (?) if I'm not mistaken.
- Paginator can't figure the posts list according to specific type [Jekyll-docs](https://jekyllrb.com/docs/pagination/).
  With the filtering code above, there might be a bug, since `paginator.posts` gets posts of the current page only, which could cause errors in some pages containing less posts ..

**Comment by untra** [comment]
Other polyglot users have requested language-specific pages. I have various ideas on how to best implement it, but I want to ask how *you* expect it to work. 

* a page specific to only a few languages should have another frontmatter option to limit what languages it builds for.  Something like:
```
lang: de
site_langs: ["de", "es"]
```

**Comment by ioab** [comment]
Yes, That's was my intention !
It's really just like you stated. Different takes, with trade-offs.
I had an idea about an extra bool tag "lang_specific", and of course, with that same thought: 

> another damn frontmatter tag

😄
I see that option (1) requires more tracking, and duplicating the lang_list in different front-matters.
For example, if we added "fr" later, changes to "de", "es" posts would be needed.

Option (2) is the closet to my use case and suffice. 
but it will remove the fallback content feature, creates use-cases conflict and breaks.

Allow me to clarify that my use case is just about Index, when listing post ...
Posts should be kept to their language sites only with no overlapping.
I don't know, but maybe templating could solve the issue.

I'll post back if any thoughts came along. Sorry for disturbing your ✈️ 😞

**Comment by jingjingzou** [comment]
I would like also to have language specific pages. For my case, option 2 will do :)

**Comment by scgupta** [comment]
I second the idea of having only language specific pages. #2 is fine, but there could generic pages (like home page, or the blog archive/list page), which has no language specific content, and has just Liquid code that generates it. When it runs for different lang, it generates appropriate listing (say /de/blog or /fr/blog ). Currently, I will just write (have yet to do, but I am guessing) blog.md for that, and I don't know if #2 will break it.
