### ISSUE TITLE
How does polyglot works with generators, like Category index example one?

### ISSUE THREAD

**Issue by LDVSOFT** [untra/polyglot#25]
Hello,

I am looking for using your awesome plugin, but before I start using it, I want to know how it actually works with generated indexes.

For example, take a look at example at Jekyll docs [here](https://jekyllrb.com/docs/plugins/#generators). Will `polyglot` run generator for different languages by itself, of will it just run it once (i.e., for default language)?

Looks like the plugin is missing the paginator support, that seems like a generating plugin, but a little different one.

**Comment by untra** [comment]
hey there!

Polyglot works not with `Jekyll::Generator` generators, but by forking the `Jekyll::Site.process` method for each language you need to build for. This means that each language has its own thread building it's fraction of the site. See [here](https://github.com/untra/polyglot#how-it-works) for more details.

I haven't explicitly tested polyglot with paginator, but I've gotten them working together before. Let me know if you have any other questions.
