### ISSUE TITLE
using jekyll uri_escape filter causes exception

### ISSUE THREAD

**Issue by scgupta** [untra/polyglot#26]
The uri_escape filter is explained at: https://jekyllrb.com/docs/templates/

Following code causes polygot to throw exception exception:

{% assign share_txt = (page.title | uri_escape ) %}

I figured out an alternative to avoid it, but it would be better for polygot to handle uri_escape filter gracefully.

{% assign share_txt = (page.title | escape('url') ) %}

Here is the exception
```
  Liquid Exception: undefined method `gsub' for nil:NilClass in _includes/socialshare.html, included in _layouts/article.html
/usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/tags/include.rb:132:in `rescue in render': undefined method `gsub' for nil:NilClass (Jekyll::Tags::IncludeTagError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/tags/include.rb:124:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:151:in `render_token'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:5:in `block in render_token_with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler.rb:80:in `profile_token_render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/profiler/hooks.rb:4:in `render_token_with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:135:in `block in render_all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:122:in `render_all'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/block.rb:108:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:210:in `block in render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:262:in `with_profiling'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:209:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/liquid-3.0.6/lib/liquid/template.rb:222:in `render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:28:in `block (2 levels) in render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:36:in `measure_bytes'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:27:in `block in render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:43:in `measure_time'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/liquid_renderer/file.rb:26:in `render!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:106:in `render_liquid'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:143:in `place_in_layouts'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/renderer.rb:70:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:179:in `block in render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:177:in `render'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/site.rb:59:in `process'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/**jekyll-polyglot-1.2.0**/lib/jekyll/polyglot/patches/jekyll/site.rb:63:in `process_active_language'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:57:in `process_language'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:24:in `block (2 levels) in process'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `fork'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `block in process'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `each'
	from /usr/local/Cellar/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/jekyll-polyglot-1.2.0/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/command.rb:26:in `process_site'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:60:in `build'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:33:in `process'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/commands/build.rb:16:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/bin/jekyll:13:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by untra** [comment]
This is not a problem with polyglot, but with your file `_includes/socialshare.html`

You are getting that error because `page.title` is not defined. The error is thrown because it is trying to `gsub` on nil.

I hope this helps!
-@untra

**Comment by scgupta** [comment]
Actually, it is defined. I verified it by spitting it out with {{ page.title }} and checking the generated html.

I even tested by modifying my template to pass it along in include as following:

{% include socialshare.html title=page.title %}

And this gives exception:
{% assign share_txt = (include.title | uri_escape ) %}

but this alternative works correctly:
{% assign share_txt = (include.title | escape('url') ) %}

If page.title (or include.title) was not defined, then the alternative would not have worked as well. That is why I think there could be some issue regarding handling of uri_escape in polyglot. 

I am using same Jekyll template that I created (with uri_escape but without polyglot) on another site https://github.com/scgupta/scgupta.github.io/blob/master/_includes/socialshare.html And it works perfectly there. So though I am not an expert in Jekyll/Ruby, it is highly unlikely that it is due to page.title not being defined.

**Comment by untra** [comment]
@scgupta 

I edited your original comment to make the stacktrace easier to read. Lets follow it!
```
Liquid Exception: undefined method `gsub' for nil:NilClass in _includes/socialshare.html
```
We know gsub is being called on nil somewhere, which is causing this to fail. But where?
```
usr/local/lib/ruby/gems/2.2.0/gems/jekyll-3.1.2/lib/jekyll/tags/include.rb:132:in `rescue in render': undefined method `gsub' for nil:NilClass (Jekyll::Tags::IncludeTagError)
```
But this tells us the error was rescued (caught) in [include.rb:132](https://github.com/jekyll/jekyll/blob/v3.1.2/lib/jekyll/tags/include.rb#L132). This also tells us the error is being thrown between lines 124 and 130 of `include.rb`

On line [128](https://github.com/jekyll/jekyll/blob/v3.1.2/lib/jekyll/tags/include.rb#L128) we call [parse_params](https://github.com/jekyll/jekyll/blob/v3.1.2/lib/jekyll/tags/include.rb#L37), which incidentally, calls gsub. Your error comes from either line `45` or `47` of `include.rb`; which one I don't know.

Maybe `page.title` is not null. But something is causing `include.title` to throw an exception. Keep digging and debugging. Try a newer version of jekyll and see if that helps. There might be problems with gsub operating on non-latin strings- who knows.

But the culprit is `include.rb`, not Polyglot.

Does this help?

**Comment by scgupta** [comment]
Humm... I didn't think of that. That is a possibility 👍 Most indic script sites are using blogger, wordpress.

My knowledge of Jekyll, Ruby, Liquid is very superficial, I know whatever I had to, to get my site done :-) But I will try to dig.

Thanks for prompt help.

**Comment by scgupta** [comment]
I updated everything: Ruby (I was using 2.2), Jekyll (I was using 3.1.2), and all the gems. And now I am not able to reproduce it anymore. So I suspect that, either it was some mismatch of versions, or a bug in `include.rb` which has been already fixed. So I am closing this.
