### ISSUE TITLE
page with multi word permalinks doesn't get relativized

### ISSUE THREAD

**Issue by scgupta** [untra/polyglot#27]
I noticed that while posts with permalinks containing dash get relativized, but pages don't.

Here is a site I am developing: https://lutf-e-ghazal.gitlab.io/en/what-is-ghazal-definition/
It is in very prelim stage, so please ignore broken links, but it has enough to demo the issue I am facing. On that page, check out the menu and target URLs, and only root ("/") and Poets (/poets/) has been relativized. I modified permalink of /poets/ to /poet-list/ and it also stopped being relativized.

I checked this repository's site branch ( https://github.com/untra/polyglot/tree/site ) and noticed that all pages have single word permalinks. I don't know if changing one of them (say "about" to "about-polyglot", both filename and permalink) will stop relativized it.

**Comment by untra** [comment]
Hi @scgupta !

This is the first time I've seen someone use polyglot for Hindi content. Neat!

I don't think long complex permalinks are a problem. I made a small change to the site to demonstrate [what I mean](http://polyglot.untra.io/a-really-long/permalink/). You can see all languages for this page have correctly parsed permalinks.

Try the following:
 * Rebuild the `_site` folder. This is where the jekyll website contents are written to. Jekyll is smart and doesn't rebuild pages it sees have already been built, but that may cause language-changed files not to relativize.
* make sure you are consistent with your file names, and organized with your content. Polyglot recognizes familiar patterns
* Make sure your corresponding pages have identical permalinks.
* Make sure the `lang:` frontmatter is correct for each page (an easy mistake to make).

I hope this helps!
-sam

**Comment by scgupta** [comment]
Really nice of you to put that example. Let me look at it. I did verify all the points you mentioned because I thought that I must be doing something silly or some typo.

**Comment by scgupta** [comment]
Hi @untra, 

I have absolutely no clue why it is happening. I looked a couple of times to see if I missed out any of the things you listed, but couldn't find any mistake. Most likely it something very silly or typo. I have checked in code in this site branch: https://github.com/lutf-e-ghazal/lutf-e-ghazal.github.io/tree/site If you have time, and can take a look to point out what is wrong, I will thankful.

**Comment by untra** [comment]
I see what you're saying now; you are right, there is a bug with long complex permalinks in the menu: starting from a [non default language](http://polyglot.untra.io/de/), the menu item for the complex permalink doesn't relativize. I think you're right; there is definitely a bug here. 🐞 

Good find! I'll work on updating the regex and making a fix for 1.2.1 . I'll include you in the credits.

I'll work on a fix for later this week. Is there a timetable for your website?
Thanks!

**Comment by untra** [comment]
I pushed out a version 1.2.2 of polyglot just now, with a fix and a few more tests that should make sure things are all stable.

Please run `gem update jekyll-polyglot`, to get the latest version, and your headers should relativize. Let me know that it works.

Cheers!
@untra

**Comment by scgupta** [comment]
Hey @untra, that fixed the problem, so I am closing it. Thanks a lot for such a quick turn around!
