### ISSUE TITLE
Feature request : handle multiple toplevel domains

### ISSUE THREAD

**Issue by kermorgant** [untra/polyglot#35]
Hello !

I have a site in two languages (sv & en) for now, using your polyglot plugin, and it's very nice !

I'm going to make the french version soon, but I have to choose if I use the .fr toplevel domain I also own, or if I continue with polyglot. In fact, I haven't thought of it enough, but I suspect I'd use polyglot in both cases.

I'm prone to make use of the .fr domain, and for now, I think of generating the 2 sites (.fi and .fr) by invoking jekyll twice, each time with a dedicated config file to redefine some variables (like site.url). Maybe polyglot could in the future manage that without the need for 2 different configs. 

I don't know, maybe this doesn't fit in the present or future scope of polyglot, but I thought I'd share my use case.
Regards
Mikael

**Comment by untra** [comment]
Hi @kermorgant !
This is the second time someone has requested different domains for their sites. I'll keep it in mind. I'm taking a break from polyglot development for awhile, however I'll keep this use-case in mind for the next version I'll work on later.

Thanks for your input. Glad the plugin is working out well for you!
Cheers,
@untra
