### ISSUE TITLE
Folder for each language

### ISSUE THREAD

**Issue by espen** [untra/polyglot#37]
This plugin looks very useful but I'm not a big fan of keeping all pages in the same directory (about.no.md). Preferably I want to have all Norwegian pages in /no/ and so on. It doesn't seem like this is configurable for pages while it is the case for posts? Would it be possible to implement this for pages?

**Comment by untra** [comment]
Polyglot does support this! From the readme:
> Files that correspond to similar routes should have identical permalinks. If you don't provide a permalink for a post, make sure you are consistent with how you place and name corresponding files.
Organized names will generate consistent permalinks when the post is rendered, and polyglot will know to build separate language versions of the website using only the files with the correct lang variable in the front matter.

So if you want to put all your Norwegian pages in a `_pages/no/` folder that's fie. Just remember that you have to be organized and consistent with your files, and to give corresponding files (`/no/about.md`, `/en/about.md`) identical permalinks (`/about/`).

If you don't give a page a permalink, jekyll generates one for you based on the file location. so `/no/about.md` would get a generated permalink that looks like `/no/about/`. Same with `/en/about.md` => `/en/about/`. Polyglot then identifies `/en/about/` and `/no/about/` as being corresponding pages for their respective languages, and readjusts the permalink to remove the language extension.

So yeah, organize the files however you want :+1: just remember:
> Be consistent with how you name and place your posts files
Always give your *pages* permalinks in the frontmatter
Don't overthink it, :wink:

**Comment by espen** [comment]
Awesome. I think perhaps this was an issue with me using `lang: no` and turns out YAML treats [no as false](https://makandracards.com/makandra/24809-yaml-keys-like-yes-or-no-evaluate-to-true-and-false). `lang: 'no'` works fine :)

**Comment by espen** [comment]
Just following up here instead of making a new issue since it's just a question:

Is it possible to localise just the content. So keep one HTML for each page and content for each language separated?

Something like https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin#52-including-translated-files

So basically have pages using either translated strings or includes to markdown content for each language:

/about.html -> include header and body
/i18n/en/about/header.md
/i18n/en/about/body.md
/i18n/nb/about/header.md
/i18n/nb/about/body.md

My goal is to completely separate content and markup so I can easily modify the HTML and have all content files in markdown files easily translated by less techy people. I'm not sure if this is the best way as there will always be a mix of content and html tags, but I think a more complex page-block with i18n translation strings is a lot better than having a complete html page for each language which will be quite tedious to manage with many languages, adding new one or doing some HTML adjustments.

**Comment by untra** [comment]
> Is it possible to localise just the content. So keep one HTML for each page and content for each language separated?

yes, this is possible. I actually use this approach to make the [Sample rich text data](http://polyglot.untra.io/fr/sample/) page on the polyglot website. The approach is to maintain a file of strings in a data directory, and use liquid tags to inject them into your markdown. Follow these steps:

1. add a [data_dir](https://github.com/untra/polyglot/blob/master/site/_config.yml#L6) to your _config.yml and directory
2. create the [string content](https://github.com/untra/polyglot/blob/master/site/_data/fr/sample.yml) for each supported language
3. use [liquid tags](https://raw.githubusercontent.com/untra/polyglot/master/site/sample.md) to inject the site.data content into your markdown/html page. You can set the pages' `lang` frontmatter to `site.data["active_lang"]` to make it work for any language.

I hope this helps! Good luck 👍 
@untra

**Comment by espen** [comment]
Ok, so I have to use YAML and not markdown blocks (files) as described/linked above?

YAML strings might be a better solution than individual files, I am still not sure what the best way to manage content within html is. Tradeoff between readability, flexibility and easy of translation.

**Comment by untra** [comment]
> YAML strings might be a better solution than individual files, I am still not sure what the best way to manage content within html is. Tradeoff between readability, flexibility and easy of translation.

You'll want to use both strategies; rich-text strings with `site.data` as described above, and whole page/posts in an entire language as described in the readme.

Rich text strings are better for building _text-lite_ site content. This strategy is good for building menus, navigation components, mixed-media components, etc. Just remember there is no fallback content for missing rich-text strings, unlike with the posts and pages.

**Comment by untra** [comment]
Pick your poison. You have two different strategies for two different kinds of content. Use each strategy appropriately, and you'll minimize the amount of work you need to do. Prioritize your rich text content over legacy blogposts and pages.

Sorry, thats the nature of i18n website development. Its just a lot of work.
