### ISSUE TITLE
cannot load such file -- jekyll-polyglot

### ISSUE THREAD

**Issue by asso1985** [untra/polyglot#38]
cannot load such file -- jekyll-polyglot after bundle exec jekyll serve

**Comment by asso1985** [comment]
I've installed  gem install jekyll-polyglot but I'm stil getting the error on jekyll 3.2.1

**Comment by espen** [comment]
You must specify it in your `Gemfile`:

```
group :jekyll_plugins do
   gem "jekyll-polyglot"
end
```
