### ISSUE TITLE
relative_url_regex if site.baseurl empty produces not matchable regex

### ISSUE THREAD

**Issue by slbug** [untra/polyglot#4]
Html string
```html
<a href="/about/">
```

Produced regex:
```regexp
/href=\"\/\/((?:[^,'\"\s\/?\.#-]+\.?)*(?:\/[^\]\[\)\(\"\'\s]*)?)\"/
```

There should be just one \/ after first quotation mark.

**Comment by untra** [comment]
@slbug  You are totes-mcgotes right. whoops, hehe. :sweat_smile: 

#5 just got pulled in. I addressed it there, and I wrote a bunch of tests to test around this bug. Nice find! Is it alright if I leave your name in the readme for credits?

Cheers,
Untra
