### ISSUE TITLE
Allow custom keys for "active language" site payload

### ISSUE THREAD

**Issue by vlsi** [untra/polyglot#41]
Currently polyglot assigns `site.active_lang` variable, however other plugins/themes might expect other key names.
For instance, minimal-mistakes expects site.locale: https://github.com/mmistakes/minimal-mistakes/blob/70c274ae56d3e07ec8cb18a35cebe101488ba53b/_layouts/default.html#L5

Would you mind making the set of keys with "current language" configurable?

**Comment by untra** [comment]
@vlsi  still interested in this feature?

**Comment by vlsi** [comment]
@untra , I am. In fact, I am using that in my own branch of polyglot.

I can elaborate on tests/documentation if you thing #68 is worth merging in.
