### ISSUE TITLE
Does not localise other collections than the "posts" collection.

### ISSUE THREAD

**Issue by PierreBongen** [untra/polyglot#43]
Documents in `_posts` will be recognised by polyglot and copied to the `_site` directory into their corresponding language directories as expected:

- `_posts/2016-11-07-welcome-to-jekyll.en.markdown` → `_site/posts/welcome-to-jekyll/index.html` with contents of `2016-11-07-welcome-to-jekyll.en.markdown`
- `_posts/2016-11-07-welcome-to-jekyll.de.markdown` → `_site/de/posts/welcome-to-jekyll/index.html` with contents of `2016-11-07-welcome-to-jekyll.de.markdown`

For other collections, only the standard language version of the document will be processed. The `site.active_lang` variable is correctly set to the active language so references to it will be substituted correctly. All links will point to the standard language version of documents. 

- `_apps/01-app1.en.md`:
````
---
title: App1 (en)
permalink: /apps/app1/
lang: en
---
App1 (en ↔ {{site.active_lang}})
[app1](/apps/app1/)
````

- `_apps/01-app1.de.md`:
````
---
title: App1 (de)
permalink: /apps/app1/
lang: de
---
App1 (de ↔ {{site.active_lang}})
````

- `_config.yml`:
````
…
collections:
    posts:
        output: true
        permalink: "/:collection/:title/"
    apps:
        output: true
…
````

will result in 

- `_site/apps/app1/index.html` with contents of `01-app1.en.md`, displaying `en → en` and a link pointing to the English version.
- `_site/de/apps/app1/index.html` with contents of __`01-app1.en.md`__, displaying __`en → de`__ and a link pointing to the __English__ version.

The following Liquid code used with the corresponding indexes of the collections _posts_ and _apps_ will reveal that it contains only the documents for the active language in case of a _posts_ document. It will contain the documents of __all__ languages for the _apps_ collection, though.

````
<ul>
{% for doc in site.collections[ 1 ].docs %}
    <li>{{ doc.path }}</li>
{% endfor %}
</ul>
````

Is the localisation of documents restricted to _pages_ and the _posts collection_? It seems as if documents with similar names and same permalinks in collections other than the _posts_ collection are not recognised so that the localisations are treated as intended. Or maybe I have overlooked some crucial details in my setup.

**Comment by untra** [comment]
I like this feature idea. Different collections are a newer Jekyll feature that Polyglot wasn't originally designed around, but should definitely provide implementation support. 👍

**Comment by vlsi** [comment]
@PierreBongen , can you please check if #45 solves the issue for you?
