### ISSUE TITLE
 fork() function is unimplemented on this machine

### ISSUE THREAD

**Issue by hetsketch** [untra/polyglot#50]
I've install `jekyll-polyglot` using bundle and got this error while execute `jekyll serve`
<pre>
C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `fork': fork() function is unimplemented on this machine (NotImplementedE
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:23:in `block in process'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `each'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:22:in `process'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/command.rb:26:in `process_site'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:63:in `build'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/build.rb:34:in `process'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/lib/jekyll/commands/serve.rb:37:in `block (2 levels) in init_with_program'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from C:/tools/ruby23/lib/ruby/gems/2.3.0/gems/jekyll-3.3.1/exe/jekyll:13:in `<top (required)>'
        from C:/tools/ruby23/bin/jekyll:23:in `load'
        from C:/tools/ruby23/bin/jekyll:23:in `<main>'
</pre>

**Comment by untra** [comment]
see [Compatability](https://github.com/untra/polyglot#compatibility)
> `Windows users will need to disable parallel_localization on their machines by setting parallel_localization: false in the _config.yml`

**Comment by hetsketch** [comment]
@untra thanks! Sorry for being inattentive
