### ISSUE TITLE
How to have different indexes for each languages?

### ISSUE THREAD

**Issue by IvanDuch** [untra/polyglot#52]
Thanks for the great job. I'm really new to Jekyll and Ruby so this might be the dumbest question ever. But I need to have a specific title, description and some changes for the nav bar in the /es/index.html.

I tried messing around with if statements but didn't find a way to have that change for that particular index.

In your example you only use a index.md file, there's no way to create two index.md? 

Thanks a lot for your great work. For now I'm doing that final editions manually but all the rest is working like a charm. 

PS: I also tried using the desc and title in config.yml  but for some reason when I define more than one desc o title the code gets messed up and it show on the top of the page.

**Comment by vlsi** [comment]
@IvanDuch , 
There are multiple ways of doing that.

1) Use index.en.md, index.ru.md, etc file names (I'm not sure if `lang: en` is required, however I add it for clarity)
Here's a sample: https://github.com/Hardella/site/tree/master/_pages

2) You can use whatever file name you want and add `permalink: /docs/introduction/` (sometimes it makes sense to isolate certain language into its own subfolder).
See example here: https://github.com/Hardella/site/blob/master/_docs/en/01-introduction.md  (note `en` before file name) vs https://github.com/Hardella/site/blob/master/_docs/01-introduction.md

**Comment by IvanDuch** [comment]
Thanks a lot vlsi! 

I just was returning to the forum because I found an alternative solution using the 
% if site.active_lang == 'en' %} statment. I was able to do all I needed. I'm trying your suggestion right now which seems to be way simpler.

**Comment by vlsi** [comment]
The only place I use `if ...` is to the one that prints language selectors (see https://github.com/Hardella/site/blob/master/_includes/masthead.html#L8-L20 )

**Comment by IvanDuch** [comment]
Thanks!
