### ISSUE TITLE
posts archive showing all languages?

### ISSUE THREAD

**Issue by teresacamachohull** [untra/polyglot#53]
hi! thanks for this great plugin - i got it to work for the sidebar and individual pages, no problem. where i'm a having a problem is with the posts. i am displaying all the posts not on the main index page but on a separate page called 'news', with the following code:  

```
<section class="archive-post-list">

   {% for post in site.posts %}
       {% assign currentDate = post.date | date: "%Y" %}
       {% if currentDate != myDate %}
           {% unless forloop.first %}</ul>{% endunless %}
           <h1>{{ currentDate }}</h1>
           <ul>
           {% assign myDate = currentDate %}
       {% endif %}
       <li><a href="{{ post.url }}"><span>{{ post.date | date: "%B %-d, %Y" }}</span> - {{ post.title }}</a></li>
       {% if forloop.last %}</ul>{% endif %}
   {% endfor %}

</section>
```

this causes all the posts to show up, be they in english or spanish. how can i make it so that only the english (default lang) show up unless the spanish switch in the sidebar is clicked, and vice versa? 

thanks for any help on this. i'm pretty new to jekyll so i'll keep trying different things but it's a little like looking around in the dark. ;)

andrea

**Comment by untra** [comment]
I don't have an environment to test this solution out for correctness at the moment, but off of the top of my head:
```
{% for post in site.posts | where:"lang",site.active_lang %}
...
{% endfor %}
```
this uses a [liquid filter](https://jekyllrb.com/docs/templates/#filters) to only pull posts with the `lang` frontmatter set to the current `site.active_lang`

Does that work?

**Comment by vlsi** [comment]
@teresacamachohull , by default collections are localized, so `site.posts` should contain posts for a specific language only.
This works provided the pages share the same permalink (see https://github.com/untra/polyglot/blob/fc8d30e1b92fbbac02fd0cf93812bec2c439c21c/lib/jekyll/polyglot/patches/jekyll/site.rb#L80 )
In case links are different there should be some way to tell which page is "english-only" and which one has translation.


Relevant polyglot code: https://github.com/untra/polyglot/blame/master/lib/jekyll/polyglot/hooks/coordinate.rb#L7-L9


For instance.
Page that prints "all posts for a given language": https://github.com/Hardella/site/blob/master/_pages/blog.en.html#L8
Implementation (simple `page.posts` loop): https://github.com/Hardella/site/blob/master/_includes/blogposts.html#L2

Result: https://hardella.com/en/blog/ (just English content thanks to polyglot automatically filtering the posts)

**Comment by teresacamachohull** [comment]
thanks for the responses! 

@untra i tried what you suggested, and nothing. 

@vlsa, i think i understand what you're saying but `sites.post` is what i have for the posts archive page and the language switch still isn't working. 

the weird thing is i got the pages working fine, and the sidebar. as far as i can tell i have the posts labeled the same with the only difference being the language marker --> [https://github.com/teresacamachohull/teresacamachohull.github.io/tree/master/_posts](https://github.com/teresacamachohull/teresacamachohull.github.io/tree/master/_posts) and the news.md page has the same code i pasted above --> [https://github.com/teresacamachohull/teresacamachohull.github.io/blob/master/news.en.md](https://github.com/teresacamachohull/teresacamachohull.github.io/blob/master/news.en.md). 

so. will try some more stuff a bit, see what i can fix..

**Comment by teresacamachohull** [comment]
ok, now it works! 

i'm not exactly sure what i did that fixed it, but for sure the pages i was naming pagname.es.md and the posts i was naming yyyy-mm-dd-postname-es.md, so maybe changing that  hyphen to a dot so they were all the same did it? also, the /news/ page where i was listing all the posts didn't have a permalink or language declared in the yaml, so maybe that was it. 

anyhow, looking good so far. thanks for a great plugin.

**Comment by teresacamachohull** [comment]
sorry - back again. is there something about githubpages that won't let this plugin work? when i build the site locally, it loads great, but then i push it to my github repository, view it at its domain ([mtcharte.net](http://mtcharte.net)) and not only is it doubling up the pages on the sidebar (which it doesn't do locally) but it's also not switching languages at all for either pages or posts.

**Comment by vlsi** [comment]
@teresacamachohull , GitHub pages allows only certain plugins (see https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L7-L38https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L7-L38 ), so polyglot is not available there.

On the other hand, you can use Travis to build the site and update gh-pages branch.

**Comment by teresacamachohull** [comment]
@vlsi thank you - like i said, i am new to all of this! but i did get Travis working finally tonight and the plugin works beautifully! thanks so much for your help and patience. ;)
