### ISSUE TITLE
undefined method `each' for nil:NilClass using Jekyll 3.3.1 and Polyglot 1.2.4

### ISSUE THREAD

**Issue by geokhoury** [untra/polyglot#55]
I am having an issue with Polyglot with Jekyll 3.3.1.

I keep getting the "`document_url_regex': undefined method `each' for nil:NilClass" when I run jekyll doctor. Sometimes I also get it with jekyll build or jekyll serve.

I don't understand what is going on, and have tried running jekyll doctor with --trace. Below is the output.

```
/something/vendor/.bundle/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:100:in `document_url_regex': undefined method `each' for nil:NilClass (NoMethodError)
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:74:in `coordinate_documents'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/hooks/coordinate.rb:8:in `block (2 levels) in <top (required)>'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/hooks/coordinate.rb:7:in `each'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/hooks/coordinate.rb:7:in `block in <top (required)>'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/hooks.rb:98:in `block in trigger'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/hooks.rb:97:in `each'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/hooks.rb:97:in `trigger'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/site.rb:165:in `read'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/commands/doctor.rb:23:in `process'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/lib/jekyll/commands/doctor.rb:15:in `block (2 levels) in init_with_program'
	from /something/vendor/.bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /something/vendor/.bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /something/vendor/.bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /something/vendor/.bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /something/vendor/.bundle/ruby/2.4.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /something/vendor/.bundle/ruby/2.4.0/gems/jekyll-3.3.1/exe/jekyll:13:in `<top (required)>'
	from /something/.rvm/gems/ruby-2.4.1/bin/jekyll:22:in `load'
	from /something/.rvm/gems/ruby-2.4.1/bin/jekyll:22:in `<main>'
	from /something/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /something/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
````

**Comment by untra** [comment]
The error is coming from [here](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L100), and is purportedly because the `languages` config is somehow nil. Not sure how that can happen. 😕 

Make sure you are on the latest of all gems for your project. Share with me your `_config.yml` polyglot specific configurations. You're not redefining the `languages` site variable anywhere else in your project, are you?

**Comment by geokhoury** [comment]
That is exactly where I traced the issue to but I still couldn't figure it out.

My _config.yml has the following section for Polyglot.

# Polyglot configuration for i18n.
languages: ["en", "de", "fr"]
default_lang: "en"
exclude_from_localizations: ["_assets", "grunt", "vendor", "node_modules", "_site"]

I am not defining languages anywhere but in the _config.yml. Most of my gems are up-to-date, but I will try again and let you know if that solves my issue.

**Comment by geokhoury** [comment]
@untra I'm still having this issue, any ideas?

Configuration file: _config.yml
       Destination: test
 Incremental build: disabled. Enable with --incremental
      Generating... 
bundler: failed to load command: jekyll (/builds/vendor/ruby/2.4.0/bin/jekyll)
NoMethodError: undefined method `-' for nil:NilClass
  /builds/vendor/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot

The first line in the trace redirects me to your patch, site.rb line 12.

  /buildsvendor/ruby/2.4.0/gems/jekyll-polyglot-1.2.4/lib/jekyll/polyglot/patches/jekyll/site.rb:12:in `prepare'

**Comment by untra** [comment]
@geokhoury [site.rb line 12](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L12)

`NoMethodError: undefined method `-' for nil:NilClass` that is saying `languages` is being set to nil. (which is what I understood from the stacktrace you shared earlier). I'm not sure how that's happening, especially given that your `_config.yaml` looks to be properly set, and that  it should be defaulting to ` ['en'] ` when not defined (see [line 10](https://github.com/untra/polyglot/blob/master/lib/jekyll/polyglot/patches/jekyll/site.rb#L10))

Can you point me to your actual repo? I'd be happy to clone it down and try it out myself, and debug it in person. At the very least, can you test the site without polyglot in use? Will it still properly build?

**Comment by untra** [comment]
Also a thought: are you using any other plugins with Jekyll that overwrite operations in `site.rb`? That might cause other issues such as poisoning the `languages`

**Comment by untra** [comment]
We put out the v 1.3.0 release of polyglot. Please give that a try, and let us know if you're still having problems.
Cheers!

**Comment by kylekirkby** [comment]
This is still an issue. We are using Jekyll 4 and running Jekyll doctor with the latest version of this plugin still fails with the above issue.

**Comment by untra** [comment]
@kylekirkby is this still a problem with jekyll-polyglot 1.5.0 ? afaik this was fixed a few versions back.
If this is still a problem for you, please make a new github issue rather than bumping an older closed issue. A stacktrace and further reproduction details are always appreciated.
