### ISSUE TITLE
String localisation and data files

### ISSUE THREAD

**Issue by sgroth** [untra/polyglot#6]
Is there a way to localise strings from data files? My use case is that I generate a menu from a `nav.yml`-file in `_data` 

    - title: "publications"
      href: "/publications/"
    
    - title: "blog"
      href: "/blog/"
and so forth. Can the respective `{{ navitem.title }}` be converted according to the il8n-Strings in `_config.yml`?

**Comment by untra** [comment]
@sgroth 
yup! I do just that on my [polyglot sample site](http://untra.github.io/polyglot/) I make a hash object in my [`_config.yml`](https://github.com/untra/polyglot/blob/site/_config.yml#L19) and then reference that object with `site.active_lang` [in my sidebar](https://github.com/untra/polyglot/blob/site/_includes/sidebar.html#L12).

Your approach to have different i18n strings stored in different .yml files in `_data/` is the right approach. Good call!

Let me know if you have any other questions.
Cheers,
Untra

**Comment by sgroth** [comment]
Thanks! 

For reference, this is how I generate the menu with entries from a data file:

    <nav role="navigation">
        {% for nav in site.data.nav %}
        <ul>
        <li>
            <a href="{% if site.active_lang == "en" %}{{site.baseurl}}en{{ nav.href }}{% else if %}{{ nav.href }}{% endif %}">{% if site.active_lang == "en" %}{{ nav.title }}{% else if site.active_lang =="de" %}{{ nav.title-de }}{% endif %}</a>
        </li>
        {% endfor %}
        </ul>
    </nav>
