### ISSUE TITLE
Plugin does not work on Github pages

### ISSUE THREAD

**Issue by ugurcanlacin** [untra/polyglot#64]
Hi,
Thank you for sharing this great plugin!
I installed it on my local and saw that it works nice. However, when I push the project to my github repository. Plugin does not work.  It is probably Github does not allow to run the plugin. After little research, I have seen this issue opened by you
https://github.com/github/pages-gem/issues/438

What is the last situation? will polygot be whitelisted soon?

Thanks

**Comment by untra** [comment]
I was informed I should [send a support request](https://github.com/github/pages-gem/issues/438#issuecomment-308125256) to github. I sent this message:
> Many Jekyll developers would like to build a github-pages website with multi-language support. There are a few plugins that achieve this functionality, but none of them are supported officially by GitHub, or are whitelisted for use alongside the pages gem. A multi-language support plugin [whitelisted](https://github.com/github/pages-gem/blob/master/lib/github-pages/plugins.rb#L20) for use with the pages gem would significantly help developers hosting their pages on GitHub to cater to a wider audience.
Please consider reviewing some of the existing multi-language plugins for whitelisting. If none of them seem satisfactory, please consider developing an official plugin that developers can use with the pages-gem.
A short list of quality existing multi-language plugins:
https://github.com/vwochnik/jekyll-language-plugin
https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin
https://github.com/untra/polyglot (my own plugin)
Thanks,
@untra 

I'll let you know when (if) I get a response 👍

**Comment by ugurcanlacin** [comment]
Thank you for your response.
I will be waiting for it! I hope it will not take log

**Comment by untra** [comment]
> Hi Untra,
Thanks for writing in! I can definitely see how enabling these plugins would be useful. I can't make any promises, but I'll let the team know that you'd like to see us allow for these in the future. Please let us know if there's anything else we can do for you in the meantime.
All the best,
Nick
@ nickcannariato GitHub Support

**Comment by ugurcanlacin** [comment]
At least they considered the request. After this, we can just wait for it. Thank you for your time. Issue can be closed.
