### ISSUE TITLE
document filters: absolute_url and relative_url

### ISSUE THREAD

**Issue by rriemann** [untra/polyglot#70]
Hey, some jekyll themes use:

    {{ "/docs/assets/" | relative_url }} => /myproject/docs/assets
    {{ "/docs/assets/" | absolute_url }} => https://jekyllrb.com/myproject/docs/assets

Is this supported? It would be nice to have a remark on this in the docs.

**Comment by untra** [comment]
If used on a language page, both filters will then be relativized for that language. This is always the rule.

For example, used on a non-default french (`fr`) site, the content becomes:
```
    {{ "/docs/assets/" | relative_url }} => /myproject/fr/docs/assets
    {{ "/docs/assets/" | absolute_url }} => https://jekyllrb.com/myproject/fr/docs/assets
```

If you want tyo use these filters without the language relativizing, you can prepend a space to the url.
```
    {{ " /docs/assets/" | relative_url }} => /myproject/docs/assets
    {{ " /docs/assets/" | absolute_url }} => https://jekyllrb.com/myproject/docs/assets
```

I hope this helps!
