### ISSUE TITLE
add a translation key in page front matter

### ISSUE THREAD

**Issue by cntlsn** [untra/polyglot#72]
Hello, I'm trying to find a way to add a translation key to the front matter of a page, so that for instance by using the same template I can have different page titles in different pages (the page title being provided in the page itself as a variable in the front matter via a dictionary key).

Basically I'm trying to do what's described here https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin#54-i18n-in-templates

But after adding the key in my `en/lang.yml` as
```
titles:
  home: "Home"
```
and setting the variable in the page front matter
```
---
layout: default
title: titles.home
---
```
the output I get is `titles.home`, and not the corresponding key...

I've also read this https://github.com/untra/polyglot/issues/34 but that won't solve my issue.
Is there a way to pass a dictionary key to a variable in the front matter?

Thanks a lot!

**Comment by untra** [comment]
When you set your frontmatter to `title: titles.home`, it tries to resolve `titles.home` to a variable. That won't succeed though, and so the title frontmatter is just set to a string `"titles.home"`

I think #34 will solve your issue, but you have to get crafty. Take a look at these two files in the example polyglot website:

https://raw.githubusercontent.com/untra/polyglot/blob/master/site/_data/en/sample.yml
https://raw.githubusercontent.com/untra/polyglot/master/site/sample.md

In my frontmatter, I use `lang: site.data["active_lang"]` to get the `active_lang`, and I use
```
{{ site.data["sample"][1] }}
```
to display the value associated with my `1` key in my `_data/en/sample.yml` file.

So for your setup, I would suggest the following frontmatter
```
---
layout: default
title: site.data["lang"]["titles"]["home"]
---
```

**Comment by cntlsn** [comment]
Hi Untra thanks a lot for your feedback!
I've tried what you suggested, but unfortunately it will again show the string `"site.data["lang"]["titles"]["home"]"` in my page title and not the corresponding dictionary key.

I have the feeling the frontmatter is always passing a string in the title field.

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

For instance, I tried something easier: in my `blog/index.html` I have
```
---
layout: default
title: site.data["lang"]
lang: site.data["active_lang"]
---
```
while in my `_includes/head.html` included in my `default.html` layout
```
<head>
...
<title>{{ page.title }}</title>
...
</head>
```

and two language files in
`_data/en/lang.yml`
`_data/it/lang.yml`

What I should get in the tab bar I guess is `"it"` or `"en"`, but what I get is `"site.data["lang"]"`

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

Last, and sorry for the long reply, I tried to replicate exactly what you suggest in https://github.com/untra/polyglot/issues/34#issuecomment-251989179
What I get in my tab bar is `http://localhost:4000/blog/`

Any suggestions?
Thanks again!

**Comment by cntlsn** [comment]
I have found a workaround.

By adding to my `_config.yml`
```
data_dir: ./_data
destination:  ./_site
title:
  en: "site title in EN"
  it: "site title in IT"
```
and to my `_include/head.html`
```
{% assign lang = site.active_lang %}
<head>
  <meta charset="UTF-8">
  {% if page.id %}
    <title>{{ page.title }} &middot; {{ site.title[lang] }}</title>
  {% else %}
    <title>{{ page.title[lang] }} &middot; {{ site.title[lang] }}</title>
  {% endif %}
...
</head>
```
and to my `blog/index.html`
```
---
layout: default
title:
  it: Tutte le news
  en: All the news
---
{% assign lang = site.active_lang %}
...
<h1>{{ page.title[lang] }}</h1>
...
```
That seems to do the job.

Still I didn't manage to find a way to store all the page titles in the `lang.yml` file and passing them to the frontmatters of the pages, instead of declaring the page title in the page file itself...

Anyway, one last question:
In my `blog/index.html` I have to add `{% assign lang = site.active_lang %}` right after the frontmatter to make the system work.
If I add `lang: site.active_lang` or `lang: site.data["active_lang"]` to the frontmatter, as I have it in the home page, it will break and won't show the `<h1>{{ page.title[lang] }}</h1>`
Any idea why it is doing that?

Thx!

**Comment by george-gca** [comment]
I was able to do this in my [template site](https://github.com/george-gca/multi-language-al-folio). My solution is having [one string defined for each language](https://github.com/george-gca/multi-language-al-folio/blob/799d10f44516018e58543d25946bb317db5844e7/_data/pt-br/strings.yml#L11) in the files [_data/LANG/strings.yml](https://github.com/george-gca/multi-language-al-folio/blob/main/_data/en-us/strings.yml) as `latest_posts: últimas postagens`, and [calling that string](https://github.com/george-gca/multi-language-al-folio/blob/799d10f44516018e58543d25946bb317db5844e7/_layouts/about.liquid#L53) in the layout of the page with the correct language with `{{ site.data[site.active_lang].strings.latest_posts }}`.

Now if you want to define this variable in the frontmatter of the page, this gets a little bit trickier. I did something like this to generate [metadata for my template](https://github.com/george-gca/multi-language-al-folio/blob/799d10f44516018e58543d25946bb317db5844e7/_includes/metadata.liquid#L41). More specifically, you can do like this:

```liquid
{% if frontmatter_var contains '.' %}
  {% assign first_part = frontmatter_var | split: '.' | first %}
  {% assign last_part = frontmatter_var | split: '.' | last %}
  {% capture result %}{{ site.data[site.active_lang].strings[first_part][last_part] }}{% endcapture %}
{% endif %}
```

This will work, for example, if `frontmatter_var = blog.title`.

Now, if you need to check if the localization string actually exists in the file `_data/LANG/strings.yml` before using it, you'll have to create a plugin for this. I had to do this for the metadata part in my code. Here is the [code for the plugin](https://github.com/george-gca/multi-language-al-folio/blob/main/_plugins/localization-exists.rb) (please mind citing my repo if you use it as per licensing and also acknowledgement). And you use it like this:

```liquid
{% if frontmatter_var contains '.' %}
  {% capture contains_localization %}{% localization_exists {{ frontmatter_var }} %}{% endcapture %}
  {% if contains_localization == 'true' %}
    {% assign first_part = frontmatter_var | split: '.' | first %}
    {% assign last_part = frontmatter_var | split: '.' | last %}
    {% capture result %}{{ site.data[site.active_lang].strings[first_part][last_part] }}{% endcapture %}
  {% else %}
    {% capture result %}{{ outer_part }}{% endcapture %}
  {% endif %}
{% endif %}
```

**Comment by ctsstc** [comment]
I'm using the following SEO plugin which uses front matter to help set the title and descriptions: 
- https://github.com/jekyll/jekyll-seo-tag

Is there any way to just override the front matter for i18n purposes while maintaining the same template? I thought about pulling the content out into an includes so that I could just duplicate the files.

Unfortunately I'm not certain how it auto generates most of the time, which I imagine is not going to be compatible with i18n, unless I can figure out how to do this override.

Is there a way that we should be setting titles and descriptions for polyglot?

**Comment by george-gca** [comment]
I don't know the inner works of both plug-ins, but since it reads from front matters and config, I figure they might not work together that well. Maybe if there is some kind of order of precedence in then. 

The good news is that what `jekyll-seo-tag` plug-in does is not that hard to do without it. So maybe a solution would be to implement it yourself. I did something like that for my template, where [there is a file](https://github.com/george-gca/multi-language-al-folio/blob/main/_includes/metadata.liquid) responsible for creating that kind of information. It is not the solution you would hope for, but it is a solution.

**Comment by george-gca** [comment]
I believe this can be closed now.
