### ISSUE TITLE
I18n_Headers attribute question

### ISSUE THREAD

**Issue by karls** [untra/polyglot#73]
Hi @untra,

Thanks for the plugin!

Maybe this is the wrong place to ask this, but why does the `{% I18n_Headers %}` code output `<link>` tags with an `i18n` attribute? I was reading the Google regional URLs support page[1] and it instructs to add something like
```<link rel="alternate" href="http://example.com/en-ie" hreflang="en-ie" />```

Note how the attribute name for the language value is `hreflang`, not `i18n`. Other tutorials suggest using `hreflang` as well — I've never seen `i18n` suggested.

Is this intentional or a bug or am I simply missing something?

[1] https://support.google.com/webmasters/answer/189077?hl=en

**Comment by untra** [comment]
👍 👍 👍 
Good catch! Thats a bug. Fix will be in #74 

Cheers,
untra

**Comment by karls** [comment]
Excellent! Thanks! 💪

Sent from my phone.
Tervitades/Regards,
Karl Sutt

**Comment by untra** [comment]
this should now be fixed in [v1.3.1](https://rubygems.org/gems/jekyll-polyglot/versions/1.3.1) . Thanks for your good eyes!

**Comment by karls** [comment]
Yep, updated the gem and it's fixed! Thanks resolving this so quickly. 👍
