### ISSUE TITLE
How do I make the default language to have a subfolder as well.

### ISSUE THREAD

**Issue by bernardomed** [untra/polyglot#76]
For SEO purposes, I need the all the languages on the website to have its own folder so instead of the default structure:

```
languages: ["en", "pt", "fr", "jp"]
default_lang: "en"
```
This folder structure is generated
```
mysite.com/ # english
mysite.com/fr # french
mysite.com/pt # portuguese
mysite.com/jp # japanese
```
I need the folder structure to be like this:

```
mysite.com/en # english
mysite.com/fr # french
mysite.com/pt # portuguese
mysite.com/jp # japanese
```

I know it might sound like a dumb question but I just found your plugin.

Thanks,

**Comment by untra** [comment]
Hi @bernardomed 👋 
In your config.yml, try this setup:

```
languages: ["en", "pt", "fr", "jp"]
default_lang: "xx"
```

this will trick polyglot into not choosing a defined default_lang. Other users have setup polyglot this way with good results. All of the languages will get their own folder, and things should still build, but you might loose some fallback content. Does that get the job done?

Cheers,
Samuel Volin

**Comment by bernardomed** [comment]
Hi @untra,

Thanks for the quick reply. I thought on doing that first but was afraid it would break something.

Thanks for your help and for this awesome plugin.

Kind regards,
Bernardo

**Comment by untra** [comment]
Nice, glad to hear this works 👍 
Feel free to open a new issue if you have any further questions.
