### ISSUE TITLE
exclude_from_localization fails with files, only works for dirs

### ISSUE THREAD

**Issue by eighthave** [untra/polyglot#79]
We have this in https://f-droid.org (staging https://fdroid.gitlab.io/fdroid-website and https://testy.at.or.at).  We have this in our __config.yml_:
```yaml
exclude_from_localization:
  - FDroid.apk
  - F-Droid.apk
  - archive
  - assets
  - css
  - favicon.png
  - repo
  - wiki
  - wp-content
```

This works fine for _assets_, _css_, and _wp-content_ which are all dirs that are part of the Jekyll project.  It also works fine for _archive_, _repo_, and _wiki_ which are not part of the Jekyll project, but are dirs provided on the same server.  It does not work for _FDroid.apk_, _F-Droid.apk_, and _favicon.png_.  The first two are local symlinks, the last is a file that's included in the Jekyll project.

Perhaps it is choking on the `.` in the names?

**Comment by eighthave** [comment]
As of at least v1.3.1, this seems to be working.

**Comment by Giszmo** [comment]
As the author of the issue you should be able to close it, not?

**Comment by eighthave** [comment]
Ok, I finally figured out all this stuff, and found some bugs.  These two spots in the code always append a `/` to the entries in `exclude_from_localization:`, so that file entries will never be matched:
* https://github.com/untra/polyglot/blob/0684b07272cf2f3885f408b137e52ddd5c20a433/lib/jekyll/polyglot/patches/jekyll/site.rb#L140
* https://github.com/untra/polyglot/blob/0684b07272cf2f3885f408b137e52ddd5c20a433/lib/jekyll/polyglot/patches/jekyll/site.rb#L148

I have an upcoming pull request that will make `exclude_from_localization:` behave in an understandable way.


Also, FYI, the v1.3.1 git tag is missing.
