### ISSUE TITLE
Are categories and tags available in different languages? 

### ISSUE THREAD

**Issue by ckreutz** [untra/polyglot#8]
This plugin looks very promising. I wonder if it also has a solution to manage tags or categories in different languages?  So I could have tags for blog posts in different languages.

**Comment by untra** [comment]
Hi @ckreutz!

This plugin is designed to provide a minimal set of lightweight tools that a programmer can use to make a commercial scale jekyll website. While Polyglot *doesn't* provide explicit support for translating tags and posts, there are ways to provide explicit string translations. You can do this by putting your tags and categories strings in a `.yml` file in your `_data/` directory. Look at [how I do the translations](https://github.com/untra/polyglot/blob/site/_config.yml#L19) for the description string on the [polyglot website](https://untra.github.io/polyglot/de). This is a common design pattern for localized applications.

You will need to use this design pattern in conjunction with how you organize your categories and tags throughout your Jekyll website.

Let me know if this helps!
@untra

**Comment by ckreutz** [comment]
Thanks for the quick reply and the tip to separate tags in an own yml file. I have to get my head around it, but now I have a good starting point. I guess it needs a bit more linking to the correct categories etc. but that is another topic.
