### ISSUE TITLE
nested default language

### ISSUE THREAD

**Issue by andreaspada** [untra/polyglot#82]
Hi! Congratulations for the great work, really awesome plugin.

I would like to know if is it possible to hack the code somewhat to have the default language also in its subfolder. I write my site in three to five languages, and I prefer to have all them in its subfolders: mysite.com/en, mysite.com/pt, mysite.com/it, mysite.com/es, etc...

Thanks!

**Comment by bernardomed** [comment]
Make the default language XX.

It worked for me.

**Comment by untra** [comment]
Yup, that's exactly the approach I'd recommend. Thanks @bernardomed ! 👍
