### ISSUE TITLE
Can the 404 page be localised?

### ISSUE THREAD

**Issue by bernardomed** [untra/polyglot#84]
I'm trying to localise the 404 page without success. 

Has anyone been able to do it?

Cheers

**Comment by untra** [comment]
404 page can have custom rich text. I like this approach:
### using `site.data` rich text
```md
# _data/fourohfour.yml
en: "four-oh-four"
es: "cuatro-cero-cuatro"
...
```
```md
# 404.md
{{ site.data["fourohfour"][site.active_lang] }}
```
This is a good strategy for including translated rich text on any page. Theres another example of this using the [sample.md](https://github.com/untra/polyglot/blob/master/site/sample.md) page. [Take a look](http://polyglot.untra.io/sample/) 👍
