### ISSUE TITLE
Any news on Polyglot 2.0?

### ISSUE THREAD

**Issue by BeMrTeal** [untra/polyglot#85]
After reading through the documentation, I'd like to know if you are still planning to release 2.0.

Cheers,

**Comment by untra** [comment]
I promise nothing!
But yes I am still working on it. Is there any feature you would really like to see or have?

**Comment by bernardomed** [comment]
- Having the default language in a folder without needing to use the 'XX' hack
- Having the ability to translate urls without using a 'ref' tag
- Sitemap plugin compatibility or sitemap generation

Thanks mate.
