### ISSUE TITLE
Simple linking within same language

### ISSUE THREAD

**Issue by raphaelmenges** [untra/polyglot#93]
Hello @untra!

I am implementing the localization of a Jekyll-based Web site with your plugin. The multi-language page generation works fine, however i cannot get the relative linking working in such a way that one stays within the same localization when navigating through the site via links. Thus, i have created a minimal [example](https://github.com/raphaelmenges/polyglot_playground/tree/7ba3972c66a204faf478b1f5b4348b905c75ef92) to make my issues reproducable. These are the following two issues you may observe in the example:

1. **Linking into localized collection items**
In index.html i am iterating over the entries of the "blog" collection and print the title `{{ entry.title }}` and use the url property `{{ entry.url }}` of each item as hyperlink. The English index.html version prints the English title and links to the English blog post. The German index.html prints the German title but links to the English blog entry, too. Of course, i would like to link to the German version of the blog entry.

2. **Linking via relative links in markdown** (might be related to #51)
I try to link from the blog entry towards a fruit from the fruits collection. As far as I understand your [readme](https://github.com/untra/polyglot#relativized-local-urls), the plugin should resolve the localized relative links so one stays automatically within the same localization. However, both the English `[Apple](/apple)` and the German `[Apfel](/apple)` blog entry version link towards the English fruit version.

Probably i have misunderstood some basic concept of your plugin, please clarify it for me!

Thanks, Raphael

**Comment by vlsi** [comment]
@raphaelmenges , have you tried `baseurl: ""` in `_config.yml`?

**Comment by raphaelmenges** [comment]
Thank you @vlsi! Changing the baseurl from `"/"` to `""` fixes both of the problems i described in this issue.
