### ISSUE TITLE
Specific permalink for "en" language?

### ISSUE THREAD

**Issue by ghost** [untra/polyglot#97]
Hello,

I'm starting a new project using your plugin, which is great btw! Also, I noticed that permalinks doesn't get localized for "en" language. For example:
- in french (default), I get `/fr/myslug`
- but in english, I get `/myslug`, but I was expecting `en/myslug`

In your sample site there is the same behaviour... Is there a way to take care/fix this behaviour, to get always a localized permalink?

Here is my `_congif.yml`:
```
# Site settings
title: SSG Boilerplate
baseurl: ""

# Build settings
destination: public
source: src
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
languages: ['fr', 'en']
default_lang: 'fr'
exclude_from_localization: ['assets']
parallel_localization: true
plugins:
  - jekyll-seo-tag
  - jekyll-polyglot
```

Thx in advance for your help!

**Comment by soykje** [comment]
@vlsi Wow you just gave me the solution! 👍 I just had to specify the `locale` variable, and everything was doing well. But it was not in the documentation, was it?
Anyway, thank you very much for your quick answer, and if still wanted/needed, here is my projects url: https://gitlab.com/soykje/ssg-boilerplate

**Comment by vlsi** [comment]
@soykje , I don't think `locale` is used by default.

In my case, `lang_vars: ["locale"]` makes `polyglot` to populate `locale` variable with current language.  I don't use that directly, however minimal-mistakes theme tries to access `site.locale` (see https://github.com/untra/polyglot/issues/41).

**Comment by soykje** [comment]
@vlsi Not sure to understand... I'm using simple Jekyll (no theme), and in fact the problem has been fixed just by specifying the `locale`. I don't have any other variable such as `lang_vars`, so it seems that the `locale` is used by default, isn't it? 😕 
It would be great to have more details on this behaviour, indeed.

**Comment by vlsi** [comment]
It is not used by default: https://github.com/untra/polyglot/search?utf8=%E2%9C%93&q=locale&type=
The only presence of `locale` is in polyglot unit tests.

**Comment by soykje** [comment]
I'm sorry but I think you lost me... 😕 In simple words what would be your answer to my initial issue, if not using the `locale` variable?

**Comment by vlsi** [comment]
@soykje , `locale` does nothing in your case.

You seem to use `site: lang: site.data.active_lang` which is not something good.

For instance:
https://gitlab.com/soykje/ssg-boilerplate/blob/master/src/index.html#L5, https://gitlab.com/soykje/ssg-boilerplate/blob/master/src/about.html#L5 and so on.

In fact, your pages should have consistent language. For instance, you should have TWO files for about. The first one with `lang: en` and the second one with `lang: fr`. They both should have `permalink: /about`, then `polyglot` will know the pages are related.

**Comment by soykje** [comment]
@vlsi How could it be possible that `locale` does nothing ?! The addition solved my issue, as I said...

Also, I don't understand your remark on my use of `lang: site.data.active_lang`, as I just followed the Polyglot official example: https://github.com/untra/polyglot/blob/master/site/sample.md 😕 

I'm open to any suggestions, but here I can't understand the point as I just followed this plugin documentation/sample... It would be nice to have more explanations, maybe.

**Comment by vlsi** [comment]
ok, I stand corrected. `lang: site.data.active_lang` should work indeed

**Comment by soykje** [comment]
@vlsi Ok, and also the addition of `locale` variable to the `_config.yml` is the correct solution to initial issue? Or is it something else to add/change?

**Comment by vlsi** [comment]
Just in case, I clone your repository, remove  `locale: 'fr'`, perform `bundle install`, then `npm run build`, and it builds the site with default fr.

For instance, `public/sample/index.html` contains French, and `public/en/sample/index.html` contains English.

There's a glitch with opengraph tag: `<meta property="og:locale" content="site.data.active_lang" />`

**Comment by soykje** [comment]
@vlsi Yes, I'm seeing this problem, maybe related to the Jekill-seo-tag plugin :/ Also, in my local environment, I've got some build issues... not you ? 😕

**Comment by soykje** [comment]
@vlsi I just fixed that by adding my own SEO tags, without the initial plugin. It works now, with the addition of a `regions` object variable in `_config.yml`.
About the initial purpose of this issue, as it is fixed, maybe we could close it?

**Comment by untra** [comment]
👍
